name: Preform quality checks

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    # allow this workflow to be called from other workflows
    workflow_call:

# Default to bash
defaults:
    run:
        shell: bash

jobs:
    # Lint job
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: npm run lint

    # Test job
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
